### ISSUE TITLE
failure with recent glibc

### ISSUE THREAD

**Issue by loveshack** [jamesodhunt/procenv#1]
I fired off a build on current development Fedora (by mistake!), and it failed with a number of errors like this:
```
util.c: In function 'container_type':
util.c:139:13: error: In the GNU C Library, "makedev" is defined
 by <sys/sysmacros.h>. For historical compatibility, it is
 currently defined by <sys/types.h> as well, but we plan to
 remove this soon. To use "makedev", include <sys/sysmacros.h>
 directly. If you did not intend to use a system-defined macro
 "makedev", you should undefine it after including <sys/types.h>. [-Werror]
  expected = makedev (5, 1);
             ^~~~~~~~~~~~~~~                    
```

The following patch allowed it to build, but you may want to re-do the conditionals and avoid having sysmacros.h in two places ; and looking at it, the second hunk isn't in your style like the first anyhow.  sysmacros.h is present back at least as far as RHEL 5, so I figured testing for glibc was good enough, avoiding extra configury. 

[procenv-sysmacros.txt](https://github.com/jamesodhunt/procenv/files/631664/procenv-sysmacros.txt)

**Comment by jamesodhunt** [comment]
Hi @loveshack - wow, sorry! I've only just seen this issue - I don't seem to have got the expected github notification. Anyhow, the fix is in release 0.48.

Thanks again!
