### ISSUE TITLE
FreeBSD sys/sysinfo.h' file not found

### ISSUE THREAD

**Issue by nunotexbsd** [jamesodhunt/procenv#19]
Hello,

I'm updating FreeBSD procenv [port](https://www.freshports.org/sysutils/procenv/) from 0.51 to 0.54.

0.51->0.52 OK
0.52->0.53 OK
0.53->0.54 NOK [log](https://termbin.com/c5tk)

Any hints on "sys/sysinfo.h' file not found"?

Thanks,
Nuno Teixeira

**Comment by jamesodhunt** [comment]
Hi @nunotexbsd - yes, you need to do the following:

```bash
$ sudo pkg install -y libsysinfo
```

**Comment by jamesodhunt** [comment]
@nunotexbsd - also fyi I've just released 0.55.

**Comment by nunotexbsd** [comment]
Hello!

```
I'm still having same error on 0.55:
(...)
===>   procenv-0.55 depends on file: /usr/local/include/sys/sysinfo.h - not found
===>   Installing existing package /packages/All/libsysinfo-0.0.3_2.txz
[140amd64-devel] Installing libsysinfo-0.0.3_2...
[140amd64-devel] Extracting libsysinfo-0.0.3_2: ......... done
===>   procenv-0.55 depends on file: /usr/local/include/sys/sysinfo.h - found
(...)
Libraries:

    libapparmor                 : no
    libselinux                  : no
    libcap                      : no
    libnuma                     : no
    libpthread                  : yes
    libkvm                      : yes
    libsysinfo / sysinfo        : no
```
Could you please take a look at my port changes and log at
https://people.freebsd.org/~eduardo/logs/procenv-0.55/ ?

Thanks,
Nuno

**Comment by jamesodhunt** [comment]
Hi @nunotexbsd - I managed to build the port using your `Makefile` as follows:

```bash
$ sudo make install CFLAGS='-I/usr/local/include -Wno-zero-length-array' LDFLAGS='-L/usr/local/lib -lsysinfo'
```

That zero length array flag is for clang only (gcc doesn't need it).

**Comment by nunotexbsd** [comment]
Hello!

That fixed build.

You can take a look at https://reviews.freebsd.org/D29689

Thanks!
Nuno Teixeira

**Comment by jamesodhunt** [comment]
Thanks @nunotexbsd. OOI, why is `-Wno-zero-length-array`, for example, not required in the `Makefile`?

**Comment by nunotexbsd** [comment]
[USES=localbase](https://docs.freebsd.org/en/books/porters-handbook/uses/#uses-localbase) as sugested in review [D29689](https://reviews.freebsd.org/D29689) do that and poudriere tests say ok 

USES=localbase replaces the use of CFLAGS and LDFLAGS in this particular port case.
 
But remember that I'm not a C programmer! Please feel free to participate in that review if you see if it is missing something!

And `-Wno-zero-length-array` was not used on poudriere testport logs that I updated with FreeBSD clang version 10.0.0. I've searched for it but it doesn't appear.

Well the program compiles and runs ok.

What you think?

Thanks,
Nuno

**Comment by jamesodhunt** [comment]
Thanks @nunotexbsd! I wasn't aware of `localbase` :smile:

**Comment by nunotexbsd** [comment]
FreeBSD | Power to serve!

I wasn't aware of it too.

Feels nice learning :)

Thanks!
