### ISSUE TITLE
MacPorts Installation

### ISSUE THREAD

**Issue by harens** [jamesodhunt/procenv#20]
Hi there @jamesodhunt 👋

I'm a project member over at [MacPorts](https://www.macports.org/), and I saw your recent PR to Homebrew https://github.com/Homebrew/homebrew-core/pull/79248. Although unfortunately they didn't accept it, I think this tool looks really interesting so I wrote a portfile for it that I'm going to submit (with man page support).

It can then be installed by running the following on macOS:

```
sudo port install procenv
```

My only question is this. Is there any particular C Standard required (e.g. 1989, 2011, etc.), or any specific compilers that you think are worth blacklisting (see [here](https://trac.macports.org/wiki/CompilerSelection)). The reason I ask is since we also provide support and pre-built binaries for much older hardware all the way back to 2009, and it would be great to get it working there.

It goes without saying, but thanks for maintaining this amazing project.

**Comment by harens** [comment]
The issue with the C Standard was resolved, and the project was added! I'll send a PR with the installation instructions shortly.

You can find the project page [here](https://ports.macports.org/port/procenv/summary).

Interestingly enough, there were build errors on macOS 10.6. Here's the [log file](https://github.com/jamesodhunt/procenv/files/6644285/10.6-log.txt) ([online log](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/59705/steps/install-port/logs/stdio)).

```c
pr_list.c:127:6: error: implicitly declaring library function 'strndup' with type 'char *(const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        s = strndup (str, 1+len);
            ^
pr_list.c:127:6: note: include the header <string.h> or explicitly provide a declaration for 'strndup'
pstring.c:131:14: error: implicit declaration of function 'wcsdup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        pstr->buf = wcsdup (str);
                    ^
1 error generated.
pstring.c:131:14: note: did you mean 'wcscmp'?
/usr/include/wchar.h:147:5: note: 'wcscmp' declared here
int     wcscmp(const wchar_t *, const wchar_t *);
        ^
pstring.c:131:12: error: incompatible integer to pointer conversion assigning to 'wchar_t *' (aka 'int *') from 'int' [-Werror,-Wint-conversion]
        pstr->buf = wcsdup (str);
                  ^ ~~~~~~~~~~~~
2 errors generated.
```

```c
string-util.c:531:10: error: implicitly declaring library function 'strndup' with type 'char *(const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                elem = strndup (start, p-start);
                       ^
string-util.c:531:10: note: include the header <string.h> or explicitly provide a declaration for 'strndup'
1 error generated.
```

Any ideas how to fix this? Thanks.

**Comment by jamesodhunt** [comment]
Hi @harens - thanks very much for creating the portfile and for raising this!

Those errors suggest that older versions of OSX may have non-standard header files (or file locations?) I only have access to an 11.4 system so can't check myself. However, a manual check of the code shows that it should compile fine as the header files mentioned (`string.h`, `wchar.h`) are being included, which is confusing.

I'll see if I can get any further information from the Travis CI: the procenv travis config does include osx as a target, but it looks like travis us currently trying to build it on Mac OS 10.13.6 (and the oldest they offer is 10.11: https://docs.travis-ci.com/user/reference/osx/). Frustratingly, the build isn't working due to a timeout installing java, so looks like I need to tweak something as I really don't need that ;)

**Comment by harens** [comment]
This issue seems to have been kindly fixed by @kencu (https://github.com/macports/macports-ports/commit/41e0efaef6705c1495cf3624b565ded3bee79526), which means that the latest 0.60 version builds fine on all the buildbots (https://github.com/macports/macports-ports/commit/b7ec9e94e27fa779d93e19d5cb6613e682916c13).

I'll therefore close this issue. Thanks @jamesodhunt for updating this really useful tool and keeping it well maintained!
