### ISSUE TITLE
On FreeBSD sys/capability.h header is deprecated

### ISSUE THREAD

**Issue by emaste** [jamesodhunt/procenv#6]
In 2014 FreeBSD's sys/capability.h header was renamed to sys/capsicum.h to avoid a conflict with the draft POSIX.1e capability header other systems (Linux) may have. sys/capability.h was retained for backwards compatibility but is deprecated and being removed in the future.

All supported and most unsupported versions of FreeBSD have sys/capsicum.h so there is no need for an autoconf test etc. for both, unless you wish to build on old FreeBSD versions with Capsicum enabled for some reason.

More information in the overall FreeBSD issue at https://bugs.freebsd.org/228878.

**Comment by jamesodhunt** [comment]
Thanks @emaste - Fixed in the [v0.52](https://github.com/jamesodhunt/procenv/releases/tag/0.52) released today.
